# Generated by Django 6.0.5 on 2026-05-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(help_text='Ej: Octavo, Noveno, Décimo', max_length=100, unique=True),
        ),
    ]
