# Generated by Django 6.0.3 on 2026-05-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_alter_curso_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paralelo',
            options={'ordering': ['curso__nombre', 'identificador']},
        ),
        migrations.AlterUniqueTogether(
            name='paralelo',
            unique_together={('curso', 'identificador')},
        ),
    ]
