# Generated by Django 6.0.3 on 2026-05-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_paralelo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='paralelo',
            name='especialidad_bachillerato',
            field=models.CharField(blank=True, choices=[('', 'Ninguna (Básica)'), ('bgu', 'Bachillerato General Unificado'), ('informatica', 'Bachillerato Técnico en Informática'), ('electricidad', 'Bachillerato Técnico en Electricidad')], default='', help_text='Solo para bachillerato. Dejar vacío para básica.', max_length=20),
        ),
    ]
