# Generated by Django 6.0.5 on 2026-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_paralelo_especialidad_bachillerato'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='tipo',
            field=models.CharField(choices=[('docente', 'Horario del Docente'), ('clase', 'Horario de Clase')], default='docente', help_text="'docente' para el panel del profesor; 'clase' para la consulta pública de horarios.", max_length=10),
        ),
    ]
