# Generated by Django 6.0.3 on 2026-05-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0006_asignatura_alter_horario_materia_horario_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='materia',
        ),
    ]
