# Generated by Django 6.0.3 on 2026-06-02 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0007_remove_horario_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='paralelo',
            name='tutor',
            field=models.ForeignKey(blank=True, help_text='Docente asignado como tutor de este paralelo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paralelos_tutorados', to='horarios.docente'),
        ),
    ]
