# Generated by Django 6.0.3 on 2026-06-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0008_paralelo_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paralelo',
            name='identificador',
            field=models.CharField(help_text='Ej: A, B, C o nombre completo', max_length=50),
        ),
    ]
