# Generated by Django 6.0.3 on 2026-06-04 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0009_alter_paralelo_identificador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Laboratorio 1, Sala de Cómputo', max_length=100, unique=True)),
                ('capacidad', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='SesionGenerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('corriendo', 'Corriendo'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=15)),
                ('modo', models.CharField(default='estandar', max_length=15)),
                ('advertencias', models.JSONField(default=list)),
                ('sin_asignar', models.JSONField(default=list)),
                ('publicado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.aula'),
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_semanales', models.PositiveSmallIntegerField()),
                ('max_horas_seguidas', models.PositiveSmallIntegerField(default=2)),
                ('permitir_doble', models.BooleanField(default=True)),
                ('dias_separados', models.BooleanField(default=False)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.asignatura')),
                ('aula_requerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.docente')),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.paralelo')),
            ],
            options={
                'unique_together': {('docente', 'asignatura', 'paralelo')},
            },
        ),
        migrations.CreateModel(
            name='BorradorHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('docente_id_cache', models.IntegerField()),
                ('curso_id_cache', models.IntegerField()),
                ('paralelo_id_cache', models.IntegerField()),
                ('asignatura_id_cache', models.IntegerField()),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.aula')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.leccion')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borradores', to='horarios.sesiongenerador')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('bloqueado', 'Bloqueado'), ('preferido', 'Preferido')], default='bloqueado', max_length=15)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='horarios.docente')),
            ],
            options={
                'unique_together': {('docente', 'dia', 'hora_inicio')},
            },
        ),
    ]
