# Generated by Django 6.0.3 on 2026-06-04 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0010_aula_sesiongenerador_horario_aula_leccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='aula',
            name='tipo',
            field=models.CharField(default='ordinaria', help_text='Ej: ordinaria, laboratorio, cancha', max_length=50),
        ),
        migrations.AlterField(
            model_name='aula',
            name='nombre',
            field=models.CharField(help_text='Ej: Laboratorio de Informática, Aula 101', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='horarios.aula'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='aula_requerida',
            field=models.ForeignKey(blank=True, help_text='Si requiere un aula específica (ej. Laboratorio)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.aula'),
        ),
        migrations.AlterField(
            model_name='sesiongenerador',
            name='advertencias',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='sesiongenerador',
            name='sin_asignar',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
