# Generated by Django 6.0.3 on 2026-06-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0011_alter_aula_options_aula_tipo_alter_aula_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='tipo',
            field=models.CharField(choices=[('docente', 'Horario del Docente'), ('clase', 'Horario de Clase'), ('atencion', 'Atención a Padres')], default='docente', help_text="'docente' para el panel del profesor; 'clase' para la consulta pública de horarios.", max_length=10),
        ),
    ]
