# Generated by Django 6.0.3 on 2026-06-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0012_alter_horario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='lugar_atencion',
            field=models.CharField(blank=True, help_text='Ej: Sala de profesores, Oficina 3', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='horarios.curso'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='paralelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='horarios.paralelo'),
        ),
    ]
