# Generated by Django 6.0.3 on 2026-06-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0013_horario_lugar_atencion_alter_horario_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='two_factor_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
