# Generated by Django 6.0.3 on 2026-06-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0014_usuario_two_factor_code_usuario_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modo_oscuro',
            field=models.BooleanField(default=False),
        ),
    ]
